default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pair
  password: 0mgp41r

development:
  <<: *default
  database: api_mvp_development

test:
  <<: *default
  database: api_mvp_test
